import {encodeString} from "../../util/util";
import {BOX_BYTE_MIN_BALANCE, BOX_FLAT_MIN_BALANCE} from "../constants";

const REWARD_PERIOD_BOX_PREFIX = encodeString("rp");
const REWARD_CLAIM_SHEET_BOX_SIZE = 1012;
const REWARD_CLAIM_SHEET_BOX_PREFIX = encodeString("c");

const REWARD_PERIOD_SIZE = 24;
const REWARD_PERIOD_BOX_SIZE = 1008;
const REWARD_PERIOD_BOX_ARRAY_LEN = 42;

const REWARD_CLAIM_SHEET_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (41 + REWARD_CLAIM_SHEET_BOX_SIZE);

export {
  REWARD_CLAIM_SHEET_BOX_PREFIX,
  REWARD_PERIOD_BOX_PREFIX,
  REWARD_CLAIM_SHEET_BOX_SIZE,
  REWARD_PERIOD_SIZE,
  REWARD_PERIOD_BOX_ARRAY_LEN,
  REWARD_PERIOD_BOX_SIZE,
  REWARD_CLAIM_SHEET_BOX_COST
};
