import {StructDefinition} from "../util/client/base/types";
import {SupportedNetwork} from "../util/commonTypes";
import {encodeString} from "../util/util";

const TOTAL_ORDER_COUNT_KEY = encodeString("order_count");
const GOVERNOR_ORDER_FEE_RATE_KEY = encodeString("governor_order_fee_rate");
const GOVERNOR_FEE_RATE_POWER_THRESHOLD_KEY = encodeString(
  "governor_fee_rate_power_threshold"
);
const ORDER_FEE_RATE_KEY = encodeString("order_fee_rate");

const STRUCTS: Record<string, StructDefinition> = {
  Entry: {
    size: 8,
    fields: {
      app_id: {
        type: "int",
        size: 8,
        offset: 0
      }
    }
  },
  Order: {
    size: 80,
    fields: {
      asset_id: {
        type: "int",
        size: 8,
        offset: 0
      },
      amount: {
        type: "int",
        size: 8,
        offset: 8
      },
      target_asset_id: {
        type: "int",
        size: 8,
        offset: 16
      },
      target_amount: {
        type: "int",
        size: 8,
        offset: 24
      },
      filled_amount: {
        type: "int",
        size: 8,
        offset: 32
      },
      collected_target_amount: {
        type: "int",
        size: 8,
        offset: 40
      },
      is_partial_allowed: {
        type: "int",
        size: 8,
        offset: 48
      },
      fee_rate: {
        type: "int",
        size: 8,
        offset: 56
      },
      creation_timestamp: {
        type: "int",
        size: 8,
        offset: 64
      },
      expiration_timestamp: {
        type: "int",
        size: 8,
        offset: 72
      }
    }
  }
} as const;

const ORDER_APP_GLOBAL_SCHEMA = {
  numUint: 16,
  numByteSlice: 16
};
const ORDER_APP_LOCAL_SCHEMA = {
  numUint: 0,
  numByteSlice: 0
};
const ORDER_APP_EXTRA_PAGES = 1;

const REGISTRY_APP_ID: Record<SupportedNetwork, number> = {
  mainnet: 2814989833,
  testnet: 734172028
};

const VAULT_APP_ID: Record<SupportedNetwork, number> = {
  mainnet: 2200606875,
  testnet: 480164661
};

const MINIMUM_BALANCE_REQUIREMENT_PER_APP = 100_000;

const APPROVAL_PROGRAM =
  "CoASY3JlYXRlX2FwcGxpY2F0aW9ugBJ1cGRhdGVfYXBwbGljYXRpb26ABGluaXSAD3Byb3Bvc2VfbWFuYWdlcoAOYWNjZXB0X21hbmFnZXKADGFzc2V0X29wdF9pboAJcHV0X29yZGVygAxjYW5jZWxfb3JkZXKAE3N0YXJ0X2V4ZWN1dGVfb3JkZXKAEWVuZF9leGVjdXRlX29yZGVygBNwdXRfcmVjdXJyaW5nX29yZGVygBZjYW5jZWxfcmVjdXJyaW5nX29yZGVygB1zdGFydF9leGVjdXRlX3JlY3VycmluZ19vcmRlcoAbZW5kX2V4ZWN1dGVfcmVjdXJyaW5nX29yZGVygAdjb2xsZWN0NhoAjg8AAQAeACoANgBLAFcAbACQAKAAuADQAPgBCAEgATgAMRiBABJENhoBFzYaAhc2GgNJFYEgEkSIATaBAUMxGYEEEkSIAbCBAUMxGYEAEkSIAbOBAUMxGYEAEkQ2GgFJFYEgEkSIAbSBAUMxGYEAEkSIAdiBAUMxGYEAEkQ2GgFJFYFAEkSIAgqBAUMxGYEAEkQ2GgEXNhoCFzYaAxc2GgQXNhoFFzYaBheIAiSBAUMxGYEAEkQ2GgEXiANCgQFDMRmBABJENhoBFzYaAhc2GgMXiAQJgQFDMRmBABJENhoBFzYaAhc2GgMXiASfgQFDMRmBABJENhoBFzYaAhc2GgMXNhoEFzYaBRc2GgYXNhoHF4gGv4EBQzEZgQASRDYaAReIB/WBAUMxGYEAEkQ2GgEXNhoCFzYaAxeICFuBAUMxGYEAEkQ2GgEXNhoCFzYaAxeICOSBAUMxGYEAEkQ2GgEXNhoCSRWBARJEiAWIgQFDNQE1AjUDgAx1c2VyX2FkZHJlc3MxAGeAB21hbmFnZXI0AWeAD3JlZ2lzdHJ5X2FwcF9pZDQDZzQDcghINQSAHHJlZ2lzdHJ5X2FwcF9hY2NvdW50X2FkZHJlc3M0BGeADHZhdWx0X2FwcF9pZDQCZ4AEnPe0jDEANAMWNAIWNAFQUFBQsIkxAIAHbWFuYWdlcmQSRIkxAIAHbWFuYWdlcmQSRIAEhweh27CJNQUxAIAHbWFuYWdlcmQSRIAQcHJvcG9zZWRfbWFuYWdlcjQFZ4AEn4pn/zQFULCJgBBwcm9wb3NlZF9tYW5hZ2VyZDUGMQA0BhJEgAdtYW5hZ2VyNAZngBBwcm9wb3NlZF9tYW5hZ2VygABngAS7av/jNAZQsIk1B4AMdXNlcl9hZGRyZXNzZDUIMQA0CBJEgQA1CTQJgQgSQAAYNAeBCDQJC4EIWBeICjY0CYEBCDUJQv/giTUKNQs1DDUNNQ41D4AMdXNlcl9hZGRyZXNzZDUQMQA0EBJEgAtvcmRlcl9jb3VudGQ1EYABbzQRFlBJgVC5RDUSNA6BAA1ENAyBAA1ENA80DRNENAoUQQAQgf///////////wE1E0IABzIHNAoINRM0DUEADDIKNA1wADUUSDQURDEWgQEJMgo0DzQOiAnAiAihNRU0DxY0EoEATwK7NA4WNBKBCE8CuzQNFjQSgRBPArs0DBY0EoEYTwK7gQAWNBKBIE8Cu4EAFjQSgShPArs0CxY0EoEwTwK7NBUWNBKBOE8CuzIHFjQSgUBPArs0ExY0EoFITwK7gAtvcmRlcl9jb3VudDQRgQEIZzQSvkg1FoAEyVPgejQQNBEWNBZQUFCwgAQac22jNBEWULCJNReADHVzZXJfYWRkcmVzc2Q1GDEANBgSRIABbzQXFlBJvUSBUBJENRk0GYEIgQi6FzUaNBmBMIEIuhdBAA00GjQZgSCBCLoXCTUaNBmBKIEIuhcURDQZgQCBCLoXNBoyCjQYiAldNBm+SDUbgATJU+B6NBg0FxY0G1BQULCABMaQmKY0FxZQsDQZvEiJNRw1HTUeNR81IDQgOAAxABJENCA4EIEGEkQ0IDgZgQASRDQgOBgyCBJENCA5GgA0HxJENCA5GgE0HhYSRDQgORoCNB0WEkQ0IDkaAzQcFhJEiTUhNSI1I4ABbzQjFlBJvUSBUBJENSQ0IYECD0Q0JIEIgQi6FzUlNCSBMIEIuhdBABY0JTQkgSCBCLoXCTUlNCI0JQ5EQgAGNCI0JRJEMgc0JIFIgQi6Fw5EMRY0IQg1JjQmgBFlbmRfZXhlY3V0ZV9vcmRlcjQjNCI0IYj/MDQkgQCBCLoXNCIyCjEAiAhVgAQXQLwpgAx1c2VyX2FkZHJlc3NkNCMWMQBQUFCwiTUnNSg1KYAMdXNlcl9hZGRyZXNzZDUqgAFvNCkWUEm9RIFQEkQ1KzEWNCcJNSw0LIATc3RhcnRfZXhlY3V0ZV9vcmRlcjQpNCg0J4j+sjQrgTCBCLoXFEEADTQrgRiBCLoXNS1CABc0K4EIgQi6FzQrgRiBCLoXNCiIBbU1LTEWgQEJMgo0K4EQgQi6FzQtiAdMNS40K4EggQi6FzQoCBY0K4EgTwK7NC40K4E4gQi6F4gFsjUvNC9ENCuBKIEIuhc0LjQvCQgWNCuBKE8CuzQrvkg1MIAEyVPgejQqNCkWNDBQUFCwgARs/SG2gAx1c2VyX2FkZHJlc3NkNCkWMQA0KBY0LhZQUFBQULA0K4EQgQi6FzQvMgqAHHJlZ2lzdHJ5X2FwcF9hY2NvdW50X2FkZHJlc3NkiAb8NCuBCIEIuhc0K4EggQi6FxJBABs0K4EQgQi6FzQrgSiBCLoXMgo0KogG0TQrvEiJNTE1MoAMdXNlcl9hZGRyZXNzZDUzMQA0MxJENDGAAW8SQQBIgAFvNDIWUEm9RIFQEkQ1NjQ2gRCBCLoXNTQ0NoEogQi6FzU1gQAWNDaBKE8CuzQ2vkg1N4AEyVPgejQzNDIWNDdQUFCwQgBUNDGAAXISQQBIgAFyNDIWUEm9RIFYEkQ1ODQ4gRCBCLoXNTQ0OIEYgQi6FzU1gQAWNDiBGE8CuzQ4vkg1OYAEb4v8nzQzNDIWNDlQUFCwQgADgQFDNDVENDQ0NTIKNDOIBf6ABCoGHis0MhY0NRZQULCJNTo1OzU8NT01PjU/NUCADHVzZXJfYWRkcmVzc2Q1QTEANEESRIALb3JkZXJfY291bnRkNUKAAXI0QhZQSYFYuUQ1QzQ/gQANRDRAND4TRDQ7gQANRDQ6gTwPRDQ6gTwYFEQ0PBRBAA2B////////////ATU8ND00PA5END5BAAwyCjQ+cAA1REg0REQxFoEBCTIKNEA0PzQ7C4gEr4gDkDVFNEAWNEOBAE8CuzQ/FjRDgQhPArs0PhY0Q4EQTwK7gQAWNEOBGE8CuzQ9FjRDgSBPArs0PBY0Q4EoTwK7NDsWNEOBME8CuzQ6FjRDgThPArs0RRY0Q4FATwK7gQAWNEOBSE8CuzIHFjRDgVBPAruAC29yZGVyX2NvdW50NEKBAQhnNEO+SDVGgARvi/yfNEE0QhY0RlBQULCABIfoaks0QhZQsIk1R4AMdXNlcl9hZGRyZXNzZDVIMQA0SBJEgAFyNEcWUEm9RIFYEkQ1STRJgRiBCLoXFEQ0SYEIgQi6FzRJgTCBCLoXCzVKNEmBAIEIuhc0SjIKNEiIBFE0Sb5INUuABG+L/J80SDRHFjRLUFBQsIAEPnsMZjRHFlCwNEm8SIk1TDVNNU6AAXI0ThZQSb1EgVgSRDVPNEyBAg9EMQCIAdE0TTRPgQiBCLoXEkQyBzRPgUiBCLoXNE+BOIEIuhcID0QxFjRMCDVQNFCAG2VuZF9leGVjdXRlX3JlY3VycmluZ19vcmRlcjRONE00TIj6gzRPgQCBCLoXNE0yCjEAiAOogATd+U+AgAx1c2VyX2FkZHJlc3NkNE4WMQBQUFCwiTVRNVI1U4AMdXNlcl9hZGRyZXNzZDVUgAFyNFMWUEm9RIFYEkQ1VTEWNFEJNVY0VoAdc3RhcnRfZXhlY3V0ZV9yZWN1cnJpbmdfb3JkZXI0UzRSNFGI+fsxFoEBCTIKNFWBEIEIuheBAIgCxTVXNFc0VYEggQi6Fw80VzRVgSiBCLoXDhBENFWBMIEIuheBAQkWNFWBME8CuzIHFjRVgUhPArs0VzRVgUCBCLoXiAEJNVg0WEQ0VYEYgQi6FzRXNFgJCBY0VYEYTwK7NFW+SDVZgARvi/yfNFQ0UxY0WVBQULCABMn2+VU0VDRTFjEANFIWNFcWUFBQUFCwNFWBEIEIuhc0WDIKgBxyZWdpc3RyeV9hcHBfYWNjb3VudF9hZGRyZXNzZIgCYDRVgTCBCLoXFEEAGzRVgRCBCLoXNFWBGIEIuhcyCjRUiAI9NFW8SIk1WjRagA9yZWdpc3RyeV9hcHBfaWRkgAtpc19lbmRvcnNlZGM1WzVcNFtENFw1XTRdRIk1XjVfNWA0XxaB////////////ARajNGAWojVhNF4WNGGjgf///////////wEWohc1YjRiiTVjNWQ0ZDRjC4GQTgo1ZTRliYAMdXNlcl9hZGRyZXNzZIgApjVpgA9yZWdpc3RyeV9hcHBfaWRkgCFnb3Zlcm5vcl9mZWVfcmF0ZV9wb3dlcl90aHJlc2hvbGRlSDVmNGY1ajRpNGoNQQAygA9yZWdpc3RyeV9hcHBfaWRkgBdnb3Zlcm5vcl9vcmRlcl9mZWVfcmF0ZWVINWdCACaAD3JlZ2lzdHJ5X2FwcF9pZGSADm9yZGVyX2ZlZV9yYXRlZUg1ZzRnNWg0aIk1a7GBBrIQgAx2YXVsdF9hcHBfaWRkshiAEWdldF90aW55X3Bvd2VyX29msho0a7IagQCyAbO0PoEEWzVsNGyJNW00bUEAHDIKNG1wADVuSDRugQASQQALNG2BADIKMgqIAKOJNW81cDVxNXI0cBRBABs0cjgQgQESRDRyOAc0cRJENHI4CDRvEkRCACA0cjgQgQQSRDRyOBQ0cRJENHI4ETRwEkQ0cjgSNG8SRIk1czV0NXU1djR0FEEAITR2OBCBARJENHY4BzR1EkQ0djgINHMPRDR2OAg1d0IAJjR2OBCBBBJENHY4FDR1EkQ0djgRNHQSRDR2OBI0cw9ENHY4EjV3NHeJNXg1eTV6NXs0exRBABmxgQGyEDR5sgA0eLIHNHqyCIEAsgGzQgAasYEEshA0ebIANHiyFDR6shI0e7IRgQCyAbOJ";
const CLEAR_PROGRAM = "CoEBQw==";

export {
  ORDER_APP_EXTRA_PAGES,
  ORDER_APP_GLOBAL_SCHEMA,
  ORDER_APP_LOCAL_SCHEMA,
  REGISTRY_APP_ID,
  STRUCTS,
  TOTAL_ORDER_COUNT_KEY,
  VAULT_APP_ID,
  MINIMUM_BALANCE_REQUIREMENT_PER_APP,
  GOVERNOR_ORDER_FEE_RATE_KEY,
  GOVERNOR_FEE_RATE_POWER_THRESHOLD_KEY,
  ORDER_FEE_RATE_KEY,
  APPROVAL_PROGRAM,
  CLEAR_PROGRAM
};
