const MINIMUM_BALANCE_REQUIREMENT_PER_BOX = 2_500;
const MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE = 400;

const MINIMUM_BALANCE_REQUIREMENT_PER_ACCOUNT = 100_000;
const MINIMUM_BALANCE_REQUIREMENT_PER_ASSET = 100_000;

const HTTP_NOT_FOUND_STATUS = 404;

export {
  MINIMUM_BALANCE_REQUIREMENT_PER_ACCOUNT,
  MINIMUM_BALANCE_REQUIREMENT_PER_ASSET,
  MINIMUM_BALANCE_REQUIREMENT_PER_BOX,
  MINIMUM_BALANCE_REQUIREMENT_PER_BOX_BYTE,
  HTTP_NOT_FOUND_STATUS
};
