import {encodeString} from "../../util/util";
import {BOX_FLAT_MIN_BALANCE, BOX_BYTE_MIN_BALANCE} from "../constants";

const MAX_LOCK_TIME = 126_144_000;
const MIN_LOCK_AMOUNT = 10_000_000;
const MIN_LOCK_AMOUNT_INCREMENT = 10_000_000;
const TWO_TO_THE_64 = 2 ** 64;

const ACCOUNT_STATE_BOX_SIZE = 32;
const SLOPE_CHANGE_BOX_SIZE = 16;

const ACCOUNT_POWER_SIZE = 48;
const ACCOUNT_POWER_BOX_SIZE = 1008;
const ACCOUNT_POWER_BOX_ARRAY_LEN = 21;

const TOTAL_POWER_SIZE = 48;
const TOTAL_POWER_BOX_SIZE = 1008;
const TOTAL_POWER_BOX_ARRAY_LEN = 21;

// Boxes
const TOTAL_POWERS = encodeString("tp");
const SLOPE_CHANGES = encodeString("sc");

const ACCOUNT_STATE_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (32 + ACCOUNT_STATE_BOX_SIZE);
const SLOPE_CHANGE_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (10 + SLOPE_CHANGE_BOX_SIZE);
const ACCOUNT_POWER_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (40 + ACCOUNT_POWER_BOX_SIZE);
const TOTAL_POWER_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (10 + TOTAL_POWER_BOX_SIZE);

export {
  ACCOUNT_STATE_BOX_SIZE,
  SLOPE_CHANGE_BOX_SIZE,
  ACCOUNT_POWER_SIZE,
  ACCOUNT_POWER_BOX_SIZE,
  ACCOUNT_POWER_BOX_ARRAY_LEN,
  TOTAL_POWER_BOX_ARRAY_LEN,
  TOTAL_POWER_BOX_SIZE,
  TOTAL_POWER_SIZE,
  TOTAL_POWERS,
  MAX_LOCK_TIME,
  MIN_LOCK_AMOUNT,
  MIN_LOCK_AMOUNT_INCREMENT,
  TWO_TO_THE_64,
  SLOPE_CHANGES,
  ACCOUNT_STATE_BOX_COST,
  SLOPE_CHANGE_BOX_COST,
  ACCOUNT_POWER_BOX_COST,
  TOTAL_POWER_BOX_COST
};
