import {encodeString} from "../../util/util";
import {BOX_BYTE_MIN_BALANCE, BOX_FLAT_MIN_BALANCE} from "../constants";

const STAKING_VOTE_MAX_OPTION_COUNT = 8;

// Box
const PROPOSAL_BOX_PREFIX = encodeString("p");
const STAKING_ATTENDANCE_BOX_PREFIX = encodeString("a");
const STAKING_VOTE_BOX_PREFIX = encodeString("v");

const STAKING_ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE = 24;
const STAKING_VOTE_BOX_SIZE = 8;

const STAKING_ATTENDANCE_BOX_COST =
  BOX_FLAT_MIN_BALANCE +
  BOX_BYTE_MIN_BALANCE * (41 + STAKING_ACCOUNT_ATTENDANCE_SHEET_BOX_SIZE);
const STAKING_VOTE_BOX_COST =
  BOX_FLAT_MIN_BALANCE + BOX_BYTE_MIN_BALANCE * (17 + STAKING_VOTE_BOX_SIZE);

export {
  STAKING_VOTE_MAX_OPTION_COUNT,
  PROPOSAL_BOX_PREFIX,
  STAKING_ATTENDANCE_BOX_PREFIX,
  STAKING_VOTE_BOX_PREFIX,
  STAKING_ATTENDANCE_BOX_COST,
  STAKING_VOTE_BOX_COST
};
