name: "New Release"

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.repository_owner == 'tinymanorg'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false  # never use caching in release builds
      - run: npm install
      # - run: npm test
      - run: npm run build
      - run: npm publish

      # - id: publish-to-npm
      #   uses: JS-DevTools/npm-publish@v4

      # - id: create-gh-release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ steps.publish-to-npm.outputs.version }}
      #     release_name: ${{ steps.publish-to-npm.outputs.version }}
